# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.1.1-60-gedf2667
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-22.04
active: false
github_repo_name: notes
project_description: Centralized repository of my Obsidian vaults and shared tooling.
project_email: blake.naccarato@gmail.com
project_name: notes
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
project_version: 0.0.0
python_version: '3.11'
year_of_project_creation: 2023
