# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 5b00e5c
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
github_repo_name: notes
project_description: Centralized repository of my Obsidian vaults and shared tooling.
project_email: blake.naccarato@gmail.com
project_name: notes
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.11'
year_of_project_creation: 2023
