stages:
  update_common:
    cmd: "python ${paths.stages.update_common}"
    deps:
      - "${paths.stages.update_common}"
      - "${paths.common}"
      - "${paths.obsidian_common}"
      - "${paths.grad_text_expand_source}"
      - "${paths.personal_text_expand_source}"
    outs:
      - "${paths.grad_common[0]}"
      - "${paths.grad_common[1]}"
      - "${paths.personal_common[0]}"
      - "${paths.personal_common[1]}"
