paths:
  data: data
  project: .
  packages: src/notes
  models: src/notes/models
  stages: src/notes/stages
  common: data/common
  obsidian_common: data/obsidian_common
  stage_update_common: src/notes/stages/update_common.py
  vaults: data/local/vaults
  grad: data/local/vaults/grad
  grad_vscode: data/local/vaults/grad/.vscode
  grad_scripts: data/local/vaults/grad/.scripts
  grad_env: data/local/vaults/grad/.env
  personal: data/local/vaults/personal
  personal_vscode: data/local/vaults/personal/.vscode
  personal_scripts: data/local/vaults/personal/.scripts
  personal_env: data/local/vaults/personal/.env
  grad_text_expand_source: data/local/vaults/grad/.obsidian/plugins/mrj-text-expand/main.js
  personal_text_expand_source: data/local/vaults/personal/.obsidian/plugins/mrj-text-expand/main.js
