paths:
  project: .
  package: src/notes
  data: data
  stages:
    sanitize_source_tags: src/notes/stages/sanitize_source_tags.py
    update_common: src/notes/stages/update_common.py
  obsidian_common: data/obsidian_common
  local: data/local
  vaults: data/local/vaults
  personal: data/local/vaults/personal
  personal_obsidian: data/local/vaults/personal/.obsidian
  personal_plugins: data/local/vaults/personal/.obsidian/plugins
  personal_links: data/local/vaults/personal/_sources/links
  personal_timestamped: data/local/vaults/personal/_timestamped
  personal_text_expand_source: data/local/vaults/personal/.obsidian/plugins/mrj-text-expand/main.js
  personal_settings:
    - data/local/vaults/personal/.obsidian/app.json
    - data/local/vaults/personal/.obsidian/appearance.json
    - data/local/vaults/personal/.obsidian/backlink.json
    - data/local/vaults/personal/.obsidian/bookmarks.json
    - data/local/vaults/personal/.obsidian/canvas.json
    - data/local/vaults/personal/.obsidian/community-plugins.json
    - data/local/vaults/personal/.obsidian/core-plugins-migration.json
    - data/local/vaults/personal/.obsidian/core-plugins.json
    - data/local/vaults/personal/.obsidian/daily-notes.json
    - data/local/vaults/personal/.obsidian/global-search.json
    - data/local/vaults/personal/.obsidian/graph.json
    - data/local/vaults/personal/.obsidian/hotkeys.json
    - data/local/vaults/personal/.obsidian/note-composer.json
    - data/local/vaults/personal/.obsidian/starred.json
    - data/local/vaults/personal/.obsidian/switcher.json
    - data/local/vaults/personal/.obsidian/templates.json
    - data/local/vaults/personal/.obsidian/types.json
    - data/local/vaults/personal/.obsidian/zk-prefixer.json
    - data/local/vaults/personal/.obsidian/snippets/callouts.css
    - data/local/vaults/personal/.obsidian/snippets/canvas.css
    - data/local/vaults/personal/.obsidian/snippets/obsidian-tasks-plugin-tweaks.css
    - data/local/vaults/personal/.obsidian/snippets/override-task-strikethroughs.css
    - data/local/vaults/personal/.obsidian/snippets/SIRVb-alternate-checkboxes.css
    - data/local/vaults/personal/.obsidian/snippets/special-panels.css
    - data/local/vaults/personal/.obsidian/plugins/cmdr/data.json
    - data/local/vaults/personal/.obsidian/plugins/cmdr/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/dataview/data.json
    - data/local/vaults/personal/.obsidian/plugins/dataview/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/find-unlinked-files/data.json
    - data/local/vaults/personal/.obsidian/plugins/find-unlinked-files/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/folder-notes/data.json
    - data/local/vaults/personal/.obsidian/plugins/folder-notes/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/mrj-text-expand/data.json
    - data/local/vaults/personal/.obsidian/plugins/mrj-text-expand/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/OA-file-hider/data.json
    - data/local/vaults/personal/.obsidian/plugins/OA-file-hider/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-advanced-uri/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-citation-plugin/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-citation-plugin/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-editor-shortcuts/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-editor-shortcuts/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-excalidraw-plugin/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-excalidraw-plugin/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-front-matter-title-plugin/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-front-matter-title-plugin/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-heading-shifter/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-heading-shifter/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-html-plugin/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-html-plugin/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-link-converter/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-link-converter/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-linter/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-linter/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-omnivore/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-omnivore/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-outliner/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-outliner/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-pandoc/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-pandoc/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-plugin-toc/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-plugin-toc/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-shellcommands/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-shellcommands/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-style-settings/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-style-settings/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-tasks-plugin/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-tasks-plugin/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-trash-explorer/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-zotero-desktop-connector/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-zotero-desktop-connector/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/omnisearch/data.json
    - data/local/vaults/personal/.obsidian/plugins/omnisearch/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/reference-map/data.json
    - data/local/vaults/personal/.obsidian/plugins/reference-map/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/tag-wrangler/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/templater-obsidian/data.json
    - data/local/vaults/personal/.obsidian/plugins/templater-obsidian/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/text-extractor/data.json
    - data/local/vaults/personal/.obsidian/plugins/text-extractor/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/cmdr/styles.css
    - data/local/vaults/personal/.obsidian/plugins/dataview/styles.css
    - data/local/vaults/personal/.obsidian/plugins/folder-notes/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-citation-plugin/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-excalidraw-plugin/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-link-converter/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-linter/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-omnivore/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-outliner/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-pandoc/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-shellcommands/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-style-settings/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-tasks-plugin/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-trash-explorer/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-zotero-desktop-connector/styles.css
    - data/local/vaults/personal/.obsidian/plugins/omnisearch/styles.css
    - data/local/vaults/personal/.obsidian/plugins/reference-map/styles.css
    - data/local/vaults/personal/.obsidian/plugins/tag-wrangler/styles.css
    - data/local/vaults/personal/.obsidian/plugins/templater-obsidian/styles.css
    - data/local/vaults/personal/.obsidian/plugins/cmdr/main.js
    - data/local/vaults/personal/.obsidian/plugins/dataview/main.js
    - data/local/vaults/personal/.obsidian/plugins/find-unlinked-files/main.js
    - data/local/vaults/personal/.obsidian/plugins/folder-notes/main.js
    - data/local/vaults/personal/.obsidian/plugins/OA-file-hider/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-advanced-uri/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-citation-plugin/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-editor-shortcuts/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-excalidraw-plugin/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-front-matter-title-plugin/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-heading-shifter/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-html-plugin/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-link-converter/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-linter/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-omnivore/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-outliner/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-pandoc/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-plugin-toc/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-shellcommands/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-style-settings/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-tasks-plugin/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-trash-explorer/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-zotero-desktop-connector/main.js
    - data/local/vaults/personal/.obsidian/plugins/omnisearch/main.js
    - data/local/vaults/personal/.obsidian/plugins/reference-map/main.js
    - data/local/vaults/personal/.obsidian/plugins/tag-wrangler/main.js
    - data/local/vaults/personal/.obsidian/plugins/templater-obsidian/main.js
    - data/local/vaults/personal/.obsidian/plugins/text-extractor/main.js
  deprecated_common: data/common
  deprecated_personal_shell_settings: data/local/vaults/personal/.obsidian/plugins/obsidian-shellcommands/data.json
  deprecated_grad: data/local/vaults/grad
  deprecated_grad_obsidian: data/local/vaults/grad/.obsidian
  deprecated_grad_plugins: data/local/vaults/grad/.obsidian/plugins
  deprecated_grad_timestamped: data/local/vaults/grad/_timestamped
  deprecated_grad_shell_settings: data/local/vaults/grad/.obsidian/plugins/obsidian-shellcommands/data.json
  deprecated_grad_settings: []
