paths:
  project: .
  package: src/notes
  data: data
  stages:
    move_timestamped: src/notes/stages/move_timestamped.py
    sync_settings: src/notes/stages/sync_settings.py
    update_common: src/notes/stages/update_common.py
  common: data/common
  common_dirs:
    - data/common/.scripts
    - data/common/.vscode
  obsidian_common: data/obsidian_common
  local: data/local
  vaults: data/local/vaults
  grad: data/local/vaults/grad
  personal: data/local/vaults/personal
  grad_obsidian: data/local/vaults/grad/.obsidian
  personal_obsidian: data/local/vaults/personal/.obsidian
  grad_plugins: data/local/vaults/grad/.obsidian/plugins
  personal_plugins: data/local/vaults/personal/.obsidian/plugins
  grad_timestamped: data/local/vaults/grad/_timestamped
  personal_timestamped: data/local/vaults/personal/_timestamped
  grad_text_expand_source: data/local/vaults/grad/.obsidian/plugins/mrj-text-expand/main.js
  personal_text_expand_source: data/local/vaults/personal/.obsidian/plugins/mrj-text-expand/main.js
  grad_common:
    - data/local/vaults/grad/.scripts
    - data/local/vaults/grad/.vscode
  personal_common:
    - data/local/vaults/personal/.scripts
    - data/local/vaults/personal/.vscode
  grad_shell_settings: data/local/vaults/grad/.obsidian/plugins/obsidian-shellcommands/data.json
  personal_shell_settings: data/local/vaults/personal/.obsidian/plugins/obsidian-shellcommands/data.json
  grad_settings:
    - data/local/vaults/grad/.obsidian/app.json
    - data/local/vaults/grad/.obsidian/appearance.json
    - data/local/vaults/grad/.obsidian/backlink.json
    - data/local/vaults/grad/.obsidian/bookmarks.json
    - data/local/vaults/grad/.obsidian/canvas.json
    - data/local/vaults/grad/.obsidian/community-plugins.json
    - data/local/vaults/grad/.obsidian/core-plugins-migration.json
    - data/local/vaults/grad/.obsidian/core-plugins.json
    - data/local/vaults/grad/.obsidian/daily-notes.json
    - data/local/vaults/grad/.obsidian/global-search.json
    - data/local/vaults/grad/.obsidian/graph.json
    - data/local/vaults/grad/.obsidian/hotkeys.json
    - data/local/vaults/grad/.obsidian/note-composer.json
    - data/local/vaults/grad/.obsidian/starred.json
    - data/local/vaults/grad/.obsidian/templates.json
    - data/local/vaults/grad/.obsidian/zk-prefixer.json
    - data/local/vaults/grad/.obsidian/snippets/callouts.css
    - data/local/vaults/grad/.obsidian/snippets/canvas.css
    - data/local/vaults/grad/.obsidian/snippets/checkbox.css
    - data/local/vaults/grad/.obsidian/plugins/dataview/data.json
    - data/local/vaults/grad/.obsidian/plugins/dataview/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/folder-notes/data.json
    - data/local/vaults/grad/.obsidian/plugins/folder-notes/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/mrj-text-expand/data.json
    - data/local/vaults/grad/.obsidian/plugins/mrj-text-expand/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/OA-file-hider/data.json
    - data/local/vaults/grad/.obsidian/plugins/OA-file-hider/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-advanced-uri/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-citation-plugin/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-citation-plugin/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-excalidraw-plugin/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-excalidraw-plugin/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-front-matter-title-plugin/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-front-matter-title-plugin/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-html-plugin/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-html-plugin/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-link-converter/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-link-converter/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-linter/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-linter/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-omnivore/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-omnivore/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-outliner/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-outliner/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-pandoc/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-pandoc/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-plugin-toc/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-plugin-toc/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-shellcommands/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-shellcommands/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-style-settings/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-trash-explorer/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-zoom/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-zoom/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-zotero-desktop-connector/data.json
    - data/local/vaults/grad/.obsidian/plugins/obsidian-zotero-desktop-connector/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/omnisearch/data.json
    - data/local/vaults/grad/.obsidian/plugins/omnisearch/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/reference-map/data.json
    - data/local/vaults/grad/.obsidian/plugins/reference-map/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/table-editor-obsidian/data.json
    - data/local/vaults/grad/.obsidian/plugins/table-editor-obsidian/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/tag-wrangler/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/templater-obsidian/data.json
    - data/local/vaults/grad/.obsidian/plugins/templater-obsidian/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/text-extractor/data.json
    - data/local/vaults/grad/.obsidian/plugins/text-extractor/manifest.json
    - data/local/vaults/grad/.obsidian/plugins/dataview/styles.css
    - data/local/vaults/grad/.obsidian/plugins/folder-notes/styles.css
    - data/local/vaults/grad/.obsidian/plugins/obsidian-citation-plugin/styles.css
    - data/local/vaults/grad/.obsidian/plugins/obsidian-excalidraw-plugin/styles.css
    - data/local/vaults/grad/.obsidian/plugins/obsidian-link-converter/styles.css
    - data/local/vaults/grad/.obsidian/plugins/obsidian-linter/styles.css
    - data/local/vaults/grad/.obsidian/plugins/obsidian-omnivore/styles.css
    - data/local/vaults/grad/.obsidian/plugins/obsidian-outliner/styles.css
    - data/local/vaults/grad/.obsidian/plugins/obsidian-pandoc/styles.css
    - data/local/vaults/grad/.obsidian/plugins/obsidian-shellcommands/styles.css
    - data/local/vaults/grad/.obsidian/plugins/obsidian-style-settings/styles.css
    - data/local/vaults/grad/.obsidian/plugins/obsidian-trash-explorer/styles.css
    - data/local/vaults/grad/.obsidian/plugins/obsidian-zoom/styles.css
    - data/local/vaults/grad/.obsidian/plugins/obsidian-zotero-desktop-connector/styles.css
    - data/local/vaults/grad/.obsidian/plugins/omnisearch/styles.css
    - data/local/vaults/grad/.obsidian/plugins/reference-map/styles.css
    - data/local/vaults/grad/.obsidian/plugins/table-editor-obsidian/styles.css
    - data/local/vaults/grad/.obsidian/plugins/tag-wrangler/styles.css
    - data/local/vaults/grad/.obsidian/plugins/templater-obsidian/styles.css
    - data/local/vaults/grad/.obsidian/plugins/dataview/main.js
    - data/local/vaults/grad/.obsidian/plugins/folder-notes/main.js
    - data/local/vaults/grad/.obsidian/plugins/OA-file-hider/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-advanced-uri/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-citation-plugin/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-excalidraw-plugin/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-front-matter-title-plugin/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-html-plugin/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-link-converter/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-linter/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-omnivore/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-outliner/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-pandoc/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-plugin-toc/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-shellcommands/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-style-settings/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-trash-explorer/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-zoom/main.js
    - data/local/vaults/grad/.obsidian/plugins/obsidian-zotero-desktop-connector/main.js
    - data/local/vaults/grad/.obsidian/plugins/omnisearch/main.js
    - data/local/vaults/grad/.obsidian/plugins/reference-map/main.js
    - data/local/vaults/grad/.obsidian/plugins/table-editor-obsidian/main.js
    - data/local/vaults/grad/.obsidian/plugins/tag-wrangler/main.js
    - data/local/vaults/grad/.obsidian/plugins/templater-obsidian/main.js
    - data/local/vaults/grad/.obsidian/plugins/text-extractor/main.js
  personal_settings:
    - data/local/vaults/personal/.obsidian/app.json
    - data/local/vaults/personal/.obsidian/appearance.json
    - data/local/vaults/personal/.obsidian/backlink.json
    - data/local/vaults/personal/.obsidian/bookmarks.json
    - data/local/vaults/personal/.obsidian/canvas.json
    - data/local/vaults/personal/.obsidian/community-plugins.json
    - data/local/vaults/personal/.obsidian/core-plugins-migration.json
    - data/local/vaults/personal/.obsidian/core-plugins.json
    - data/local/vaults/personal/.obsidian/daily-notes.json
    - data/local/vaults/personal/.obsidian/global-search.json
    - data/local/vaults/personal/.obsidian/graph.json
    - data/local/vaults/personal/.obsidian/hotkeys.json
    - data/local/vaults/personal/.obsidian/note-composer.json
    - data/local/vaults/personal/.obsidian/starred.json
    - data/local/vaults/personal/.obsidian/templates.json
    - data/local/vaults/personal/.obsidian/zk-prefixer.json
    - data/local/vaults/personal/.obsidian/snippets/callouts.css
    - data/local/vaults/personal/.obsidian/snippets/canvas.css
    - data/local/vaults/personal/.obsidian/snippets/checkbox.css
    - data/local/vaults/personal/.obsidian/plugins/cmdr/data.json
    - data/local/vaults/personal/.obsidian/plugins/cmdr/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/dataview/data.json
    - data/local/vaults/personal/.obsidian/plugins/dataview/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/folder-notes/data.json
    - data/local/vaults/personal/.obsidian/plugins/folder-notes/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/mrj-text-expand/data.json
    - data/local/vaults/personal/.obsidian/plugins/mrj-text-expand/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/OA-file-hider/data.json
    - data/local/vaults/personal/.obsidian/plugins/OA-file-hider/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-advanced-uri/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-citation-plugin/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-citation-plugin/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-excalidraw-plugin/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-excalidraw-plugin/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-front-matter-title-plugin/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-front-matter-title-plugin/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-html-plugin/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-html-plugin/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-link-converter/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-link-converter/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-linter/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-linter/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-omnivore/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-omnivore/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-outliner/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-outliner/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-pandoc/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-pandoc/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-plugin-toc/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-plugin-toc/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-shellcommands/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-shellcommands/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-style-settings/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-trash-explorer/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-zoom/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-zoom/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-zotero-desktop-connector/data.json
    - data/local/vaults/personal/.obsidian/plugins/obsidian-zotero-desktop-connector/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/omnisearch/data.json
    - data/local/vaults/personal/.obsidian/plugins/omnisearch/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/reference-map/data.json
    - data/local/vaults/personal/.obsidian/plugins/reference-map/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/table-editor-obsidian/data.json
    - data/local/vaults/personal/.obsidian/plugins/table-editor-obsidian/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/tag-wrangler/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/templater-obsidian/data.json
    - data/local/vaults/personal/.obsidian/plugins/templater-obsidian/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/text-extractor/data.json
    - data/local/vaults/personal/.obsidian/plugins/text-extractor/manifest.json
    - data/local/vaults/personal/.obsidian/plugins/cmdr/styles.css
    - data/local/vaults/personal/.obsidian/plugins/dataview/styles.css
    - data/local/vaults/personal/.obsidian/plugins/folder-notes/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-citation-plugin/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-excalidraw-plugin/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-link-converter/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-linter/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-omnivore/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-outliner/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-pandoc/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-shellcommands/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-style-settings/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-trash-explorer/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-zoom/styles.css
    - data/local/vaults/personal/.obsidian/plugins/obsidian-zotero-desktop-connector/styles.css
    - data/local/vaults/personal/.obsidian/plugins/omnisearch/styles.css
    - data/local/vaults/personal/.obsidian/plugins/reference-map/styles.css
    - data/local/vaults/personal/.obsidian/plugins/table-editor-obsidian/styles.css
    - data/local/vaults/personal/.obsidian/plugins/tag-wrangler/styles.css
    - data/local/vaults/personal/.obsidian/plugins/templater-obsidian/styles.css
    - data/local/vaults/personal/.obsidian/plugins/cmdr/main.js
    - data/local/vaults/personal/.obsidian/plugins/dataview/main.js
    - data/local/vaults/personal/.obsidian/plugins/folder-notes/main.js
    - data/local/vaults/personal/.obsidian/plugins/OA-file-hider/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-advanced-uri/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-citation-plugin/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-excalidraw-plugin/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-front-matter-title-plugin/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-html-plugin/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-link-converter/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-linter/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-omnivore/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-outliner/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-pandoc/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-plugin-toc/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-shellcommands/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-style-settings/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-trash-explorer/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-zoom/main.js
    - data/local/vaults/personal/.obsidian/plugins/obsidian-zotero-desktop-connector/main.js
    - data/local/vaults/personal/.obsidian/plugins/omnisearch/main.js
    - data/local/vaults/personal/.obsidian/plugins/reference-map/main.js
    - data/local/vaults/personal/.obsidian/plugins/table-editor-obsidian/main.js
    - data/local/vaults/personal/.obsidian/plugins/tag-wrangler/main.js
    - data/local/vaults/personal/.obsidian/plugins/templater-obsidian/main.js
    - data/local/vaults/personal/.obsidian/plugins/text-extractor/main.js
