paths:
  project: .
  package: src/notes
  data: data
  external: data/external
  stages:
    move_timestamped: src/notes/stages/move_timestamped.py
    update_common: src/notes/stages/update_common.py
  common: data/common
  common_dirs:
    - data/common/.scripts
    - data/common/.vscode
  obsidian_common: data/obsidian_common
  local: data/local
  vaults: data/local/vaults
  grad: data/local/vaults/grad
  personal: data/local/vaults/personal
  grad_timestamped: data/local/vaults/grad/_timestamped
  personal_timestamped: data/local/vaults/personal/_timestamped
  grad_common:
    - data/local/vaults/grad/.scripts
    - data/local/vaults/grad/.vscode
  personal_common:
    - data/local/vaults/personal/.scripts
    - data/local/vaults/personal/.vscode
  grad_text_expand_source: data/local/vaults/grad/.obsidian/plugins/mrj-text-expand/main.js
  personal_text_expand_source: data/local/vaults/personal/.obsidian/plugins/mrj-text-expand/main.js
