paths:
  requirements: requirements.txt
  dev_requirements: .tools/requirements
  package: src/notes
  stages: src/notes/stages
  models: src/notes/models
  paths_module: src/notes/models/paths.py
  data: data
  examples: data/examples
  project_schema: data/schema
