# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2023-02-10T16:53:31+00:00

# flake8: noqa: A003

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Accessed(BaseModel):
    date_parts: List[List[int]] = Field(..., alias="date-parts")


class AuthorItem(BaseModel):
    family: Optional[str] = None
    given: Optional[str] = None
    literal: Optional[str] = None


class Issued(BaseModel):
    date_parts: List[List[int]] = Field(..., alias="date-parts")


class DirectorItem(BaseModel):
    literal: str


class EditorItem(BaseModel):
    family: str
    given: str


class CollectionEditorItem(BaseModel):
    family: str
    given: str


class Submitted(BaseModel):
    date_parts: List[List[Union[int, str]]] = Field(..., alias="date-parts")


class ModelItem(BaseModel):
    id: str
    abstract: Optional[str] = None
    accessed: Optional[Accessed] = None
    author: Optional[List[AuthorItem]] = None
    citation_key: str = Field(..., alias="citation-key")
    container_title: Optional[str] = Field(None, alias="container-title")
    DOI: Optional[str] = None
    issued: Optional[Issued] = None
    language: Optional[str] = None
    license: Optional[str] = None
    page: Optional[str] = None
    publisher: Optional[str] = None
    section: Optional[str] = None
    source: Optional[str] = None
    title: str
    title_short: Optional[str] = Field(None, alias="title-short")
    type: str
    URL: Optional[str] = None
    ISBN: Optional[str] = None
    number_of_pages: Optional[str] = Field(None, alias="number-of-pages")
    container_title_short: Optional[str] = Field(None, alias="container-title-short")
    ISSN: Optional[str] = None
    issue: Optional[str] = None
    volume: Optional[str] = None
    number: Optional[str] = None
    note: Optional[str] = None
    dimensions: Optional[str] = None
    director: Optional[List[DirectorItem]] = None
    PMID: Optional[str] = None
    collection_title: Optional[str] = Field(None, alias="collection-title")
    editor: Optional[List[EditorItem]] = None
    event_place: Optional[str] = Field(None, alias="event-place")
    publisher_place: Optional[str] = Field(None, alias="publisher-place")
    edition: Optional[str] = None
    collection_editor: Optional[List[CollectionEditorItem]] = Field(
        None, alias="collection-editor"
    )
    event_title: Optional[str] = Field(None, alias="event-title")
    genre: Optional[str] = None
    PMCID: Optional[str] = None
    authority: Optional[str] = None
    call_number: Optional[str] = Field(None, alias="call-number")
    submitted: Optional[Submitted] = None


class Model(BaseModel):
    __root__: List[ModelItem]
