[build-system]
requires = ["flit_core==3.9.0"]
build-backend = "flit_core.buildapi"

[project]
name = "notes_pipeline"
version = "0.0.0"
description = "Data pipeline"
dependencies = ["dulwich>=0.21.7", "pydantic>=2.9.2", "pyyaml>=6.0.2", "typer>=0.9.0"]
[project.scripts]
"notes-pipeline" = "notes_pipeline.__main__:main"
"notes_pipeline" = "notes_pipeline.__main__:main"

[tool.fawltydeps]
deps = ["packages/pipeline/pyproject.toml"]
code = ["packages/pipeline/notes_pipeline"]
ignore_undeclared = [
  # ? This project
  "notes",
  # ? Workspaces
  "lookback",
  "notes_dev",
  "notes_pipeline",
]
