name: "locks"
on: ["push", "workflow_dispatch"]
jobs:
  lock:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: ["ubuntu-latest", "windows-latest", "macos-13", "macos-14"]
    steps:
      - uses: "actions/checkout@v4"
      - run: "curl -LsSf https://astral.sh/uv/install.sh | sh"
      - run: "uv pip compile --python-version ${{ matrix.python-version }} pyproject.toml"
