name: "locks"
on: ["workflow_dispatch"]
jobs:
  lock:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - run: "pip install uv"
      - run: "uv pip compile --python-version 3.11 pyproject.toml"
