# Publish release
name: "release"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: True
on:
  release:
    types: ["published"]
defaults:
  run:
    shell: "pwsh"
jobs:
  release:
    permissions:
      contents: "write"
      id-token: "write"
      attestations: "write"
    runs-on: "ubuntu-22.04"
    environment:
      name: "release"
      url: "https://pypi.org/p/notes"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
      - uses: "astral-sh/setup-uv@2e657c127d5b1635d5a8e3fa40e0ac50a5bf6992" # v3.2.2
        with:
          version: "0.6.17"
          enable-cache: true
          cache-dependency-glob: |
            **/uv.lock
            .github/workflows/**
      - run: "./Invoke-Uv.ps1 -Build"
      - uses: actions/attest-build-provenance@5e9cb68e95676991667494a6a4e59b8a2f13e1d0 # v1.3.3
        with:
          subject-path: "dist/**"
      - run: "gh release upload '${{ github.event.release.tag_name }}' dist/**"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
      - uses: "pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0" # v1.9.0
  changerelease:
    needs: "release"
    permissions:
      contents: "write"
    uses: "./.github/workflows/changerelease.yml"
