name: "sphinx"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["docs/**", "README.md", "CHANGELOG.md", "requirements.txt"]

permissions:
  contents: "read"
  pages: "write"
  id-token: "write"

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      - run: "sphinx-build -EaT docs _site"
      - uses: "actions/upload-pages-artifact@v3.0.0"
  deploy:
    if: "${{ !(github.event_name == 'pull_request') }}"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: "ubuntu-latest"
    needs: "build"
    steps:
      - id: "deployment"
        uses: "actions/deploy-pages@v4.0.2"
